version: '3.8'
services:
  postgres:
    image: postgres:12
    volumes:
      - ./datosPSQL:/var/lib/postgresql/data
    restart: always
    ports: 
      - "5432:5432"

    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=login

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

  apache:
    image: httpd:2.4
    container_name: my-apache-app
    ports:
      - '81:81'
    volumes:
      - './html:/usr/local/apache2/htdocs'
    restart: always
    environment:
      TZ: 'America/Santiago'  # Configura la zona horaria según tu ubicación